### ISSUE TITLE
Show shortcut on UI Widget

### ISSUE THREAD

**Issue by ArieLeo** [Jrome90/ConnectEdges#1]
Any chance you can show the hotkey on the UI Widget, ie bellow the parameter?

**Comment by Jrome90** [comment]
Hotkeys are displayed when the addon preference: "Display Hotkeys" is checked.

**Comment by ArieLeo** [comment]
> Hotkeys are displayed when the addon preference: "Display Hotkeys" is checked.

Ooooh how could i miss this button, thanks a lot.
